In [1]:
import numpy as np

In [2]:
a1=np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
a1.ndim

1

In [4]:
a2=np.array([[1,2,3],
             [4,5,6],
             [6,7,8]])
a2

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [5]:
a2.ndim

2

In [6]:
a1.dtype,a2.dtype

(dtype('int32'), dtype('int32'))

In [7]:
a1.size

3

In [8]:
import pandas as pd

In [9]:
df=pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6
2  6  7  8

In [10]:
 ones=np.ones((2,3),dtype=int)

In [11]:
ones

array([[1, 1, 1],
       [1, 1, 1]])

In [12]:
 range_array=np.arange(2,20,4)

In [13]:
range_array

array([ 2,  6, 10, 14, 18])

In [14]:
np.random.seed(0)
random_array=np.random.random((2,3))
random_array

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411]])

In [15]:
random_array_2=np.random.randint(0,12,size=(2,3))

In [16]:
random_array_2

array([[ 4,  7,  6],
       [ 8,  8, 10]])

## 3. viewing array and matrices

In [17]:
a3=np.array([  [[1,2,3],
                [2,4,6],
                [6,7,9]],
               [[2,3,4],
                [4,2,5],
                [5,6,7]]  ])

In [18]:
a3

array([[[1, 2, 3],
        [2, 4, 6],
        [6, 7, 9]],

       [[2, 3, 4],
        [4, 2, 5],
        [5, 6, 7]]])

In [19]:
a3[0]

array([[1, 2, 3],
       [2, 4, 6],
       [6, 7, 9]])

In [20]:
a3.shape

(2, 3, 3)

In [21]:
a3

array([[[1, 2, 3],
        [2, 4, 6],
        [6, 7, 9]],

       [[2, 3, 4],
        [4, 2, 5],
        [5, 6, 7]]])

In [22]:
a3[:2,:1,:2]

array([[[1, 2]],

       [[2, 3]]])

In [23]:
a4=np.random.randint(10,size=(2,3,4,5))
a4

array([[[[1, 6, 7, 7, 8],
         [1, 5, 9, 8, 9],
         [4, 3, 0, 3, 5],
         [0, 2, 3, 8, 1]],

        [[3, 3, 3, 7, 0],
         [1, 9, 9, 0, 4],
         [7, 3, 2, 7, 2],
         [0, 0, 4, 5, 5]],

        [[6, 8, 4, 1, 4],
         [9, 8, 1, 1, 7],
         [9, 9, 3, 6, 7],
         [2, 0, 3, 5, 9]]],


       [[[4, 4, 6, 4, 4],
         [3, 4, 4, 8, 4],
         [3, 7, 5, 5, 0],
         [1, 5, 9, 3, 0]],

        [[5, 0, 1, 2, 4],
         [2, 0, 3, 2, 0],
         [7, 5, 9, 0, 2],
         [7, 2, 9, 2, 3]],

        [[3, 2, 3, 4, 1],
         [2, 9, 1, 4, 6],
         [8, 2, 3, 0, 0],
         [6, 0, 6, 3, 3]]]])

In [24]:
a4[:2,:3,:1,:4]

array([[[[1, 6, 7, 7]],

        [[3, 3, 3, 7]],

        [[6, 8, 4, 1]]],


       [[[4, 4, 6, 4]],

        [[5, 0, 1, 2]],

        [[3, 2, 3, 4]]]])

## 4. manipulate and compare different array

In [25]:
a1


array([1, 2, 3])

In [26]:
ones=np.ones(3)
ones

array([1., 1., 1.])

In [27]:
a1+1

array([2, 3, 4])

In [28]:
a1-1

array([0, 1, 2])

In [29]:
a1*2

array([2, 4, 6])

In [30]:
       a2

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [31]:
a1*a2

array([[ 1,  4,  9],
       [ 4, 10, 18],
       [ 6, 14, 24]])

In [32]:
a3

array([[[1, 2, 3],
        [2, 4, 6],
        [6, 7, 9]],

       [[2, 3, 4],
        [4, 2, 5],
        [5, 6, 7]]])

In [33]:
a2*a3

array([[[ 1,  4,  9],
        [ 8, 20, 36],
        [36, 49, 72]],

       [[ 2,  6, 12],
        [16, 10, 30],
        [30, 42, 56]]])

In [34]:
a1*a3

array([[[ 1,  4,  9],
        [ 2,  8, 18],
        [ 6, 14, 27]],

       [[ 2,  6, 12],
        [ 4,  4, 15],
        [ 5, 12, 21]]])

In [36]:
a9=np.array([[1, 2, 3],
       [4, 5, 6]
       ])

In [37]:
a9*a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [40]:
a9 = np.array([[1, 2, 3],
               [4, 5, 6]])
a3 = np.array([[[1, 2, 3],
                [2, 4, 6],
                [6, 7, 9]],
               [[2, 3, 4],
                [4, 2, 5],
                [5, 6, 7]]])
a9 = a9.reshape((2, 3,1))

result = a3 * a9
print(result)


[[[ 1  2  3]
  [ 4  8 12]
  [18 21 27]]

 [[ 8 12 16]
  [20 10 25]
  [30 36 42]]]


In [43]:
a2

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [42]:
a1

array([1, 2, 3])

In [41]:
a2/a1

array([[1.        , 1.        , 1.        ],
       [4.        , 2.5       , 2.        ],
       [6.        , 3.5       , 2.66666667]])

In [44]:
a2//a1

array([[1, 1, 1],
       [4, 2, 2],
       [6, 3, 2]])

In [45]:
a9

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])